---
- block:

  - name: RedHat/CentOS/Fedora | Add OpenDistro repo
    yum_repository:
      file: opendistro
      name: opendistro_repo
      description: Opendistro yum repository
      baseurl: "{{ package_repos.yum.opendistro.baseurl }}"
      gpgkey: "{{ package_repos.yum.opendistro.gpg }}"
      gpgcheck: true

  tags:
    - install
